### ISSUE TITLE
每篇文章都有自己的评论，不是全局的

### ISSUE THREAD

**Issue by b9348** [3Alan/site#11]
每篇文章都有自己的评论，不是全局的

_Originally posted by @3Alan in https://github.com/3Alan/site/discussions/7#discussioncomment-3949484_
   这个 https://b9348.gitee.io 我添加了，用手机打开的，第一次打开加载不出来评论区咋办，大佬请问你知道咋弄不。我必须翻页以后才能加载出来评论区

**Comment by b9348** [comment]
用电脑就没这问题

**Comment by 3Alan** [comment]
[#7 ](https://github.com/3Alan/site/discussions/7#discussioncomment-3950803)
