### ISSUE TITLE
博客功能咨询

### ISSUE THREAD

**Issue by asang24** [3Alan/site#50]
你好，首先我对前端不熟悉， 想知道也有博文右下方的   
<img width="644" alt="image" src="https://github.com/3Alan/site/assets/25120283/5e6644cb-85d1-42bb-9d0a-679cd8186ef5">
这个效果，我在自己的docusaurus博客里应该怎么做呢

**Comment by 3Alan** [comment]
你需要swizzling相应的博客组件，然后在相应的位置插入你想要展示的内容/组件
swizzling可以参考：
https://docusaurus.io/docs/swizzling
https://www.alanwang.site/posts/blog-guides/docusaurus-comment#swizzling-docusaurus-%E5%86%85%E9%83%A8%E7%BB%84%E4%BB%B6

然后捐献的组件实现可以参考
https://github.com/3Alan/site/blob/main/src/components/donate/index.tsx
https://github.com/3Alan/site/blob/main/src/theme/BlogPostPage/index.tsx#L65

**Comment by asang24** [comment]
tks, 尝试了下 没成功显示。。 感谢
